CC=g++
CFLAGS = -o
CPPTO = TemplateOverloading.cpp
NAMETO = TemplateOverloading
CPPBT = Hidato Puzzle.cpp
NAMEBT = BasicTO

TO:
	$(CC) $(CPPTO) $(CFLAGS) $(NAMETO)
	
BT:
	$(CC) $(CPPBT) $(CFLAGS) $(NAMEBT)

all:
	$(CC) $(CPPTO) $(CFLAGS) $(NAMETO)
	$(CC) $(CPPBT) $(CFLAGS) $(NAMEBT)

clean:
	rm $(NAMETO) $(NAMEBT)
